# Generated by Django 3.2.16 on 2022-11-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_folder_parent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.CharField(default='', max_length=30),
        ),
    ]
