# Generated by Django 3.2.16 on 2022-11-16 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_folder_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
