# Generated by Django 3.2.16 on 2022-11-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_img_or_txt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
