# Generated by Django 3.2.16 on 2022-11-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221116_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='is_img_or_txt',
            new_name='readable',
        ),
    ]
